apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-password-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-password-operator-role
rules:
  - apiGroups: [example.com]
    resources: [redisclusterpasswords]
    verbs: [list, watch, patch, get]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch, create, patch, update]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-password-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-password-operator-role
subjects:
  - kind: ServiceAccount
    name: redis-password-operator
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-password-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-password-operator
  template:
    metadata:
      labels:
        app: redis-password-operator
    spec:
      serviceAccountName: redis-password-operator
      containers:
        - name: operator
          image: redis-password-operator:latest
          imagePullPolicy: IfNotPresent
